name: sample_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.1.1
  google_fonts: ^6.2.0
  http: ^1.2.1
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  rxdart: ^0.27.7
  skeletonizer: ^1.1.2+1
  talker_logger: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
